### ISSUE TITLE
CW2

### ISSUE THREAD

**Issue by kizukkk** [oleksandrblazhko/ai202-markovskij#10]
### Контрольна робота №2

**Comment by kizukkk** [comment]
### Завдання 1
### Поруршення умови атомарності (FR1), завершеності (FR2) та безкоштовності реалізації (FR3)

|     FR    |              Опис функціональної вимоги             |
|:---------:|:---------------------------------------------------:|
| **_FR1_** |          Авторизувати Скульптора та Менеджера на сервісі         |
|   FR1.1   |           Скульптор та Менеджер надає дані авторизації          |
|   FR1.2   |        ПП надає доступ до функціоналу сервісу       |
| **_FR2_** |              Надати дані               |
|   FR2.1   | ПП надає дані на профіль                            |
|   FR2.2   |          Скульптор підтверджує отримування даних    |
| **_FR3_** |                    Скласти графік в Excel                   |
|   FR3.1   |              ПП надає список майстерень             |
|   FR3.2   |    Менеджер складає графік, за допомогою <br> Excel, відвідування майстерень  |

**Comment by kizukkk** [comment]
### Завдання 2

Розподілена система - 4
Через специфікацію вибраного середовища розробки ПП, досягти повної розподіленості компонентів Застосунок, Сервер обробки інформації та База даних досягається використанням додаткових технологій, що призводить до ускладнення проєкту.

Спеціальні вимоги до навчання користувачів - 2
В програмному продукті  є два активних користувачи: Менеджер та Скульптор.
Через розподілення функціоналу продукту та його загальну спрощеність від користувачів потребується мінімальні досвід в взаємодії з класичними застосунками з наданням послуг (наприклад Банквівські застосунки або Київ цифровий).

**Comment by oleksandrblazhko** [comment]
оцінка = 3 бали
